package uz.behzod.eightytwenty.utils.constants

object BroadcastConstants {
    const val BROADCAST_ACTION_IMPORT_ONGOING = "BROADCAST_ACTION_IMPORT_ONGOING"
    const val BROADCAST_ACTION_IMPORT_SUCCESS = "BROADCAST_ACTION_IMPORT_SUCCESS"
    const val BROADCAST_ACTION_IMPORT_FAILED = "BROADCAST_ACTION_IMPORT_FAILED"

    const val BROADCAST_INTENT_STATUS = "BROADCAST_INTENT_STATUS"
    const val BROADCAST_INTENT_DATA = "BROADCAST_INTENT_DATA"
    const val BROADCAST_INTENT_EXTRA = "BROADCAST_INTENT_EXTRA"
}